version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    container_name: data_viz_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: data_viz
    ports:
      - "5432:5432"
